[tool.poetry]
name = "cursed-python"
version = "0.1.0"
description = ""
authors = ["Jack92829"]

packages = [
    { include = "cursed_python" }
]

[tool.poetry.dependencies]
python = ">=3.7,<=3.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
